name: Publish to npm

on:
  release:
    types: [released]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Upgrade npm CLI
        run: npm install -g npm@latest

      - name: Install and Build with Yarn
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Publish to npm
        run: npm publish --access public --provenance
